import type { AIAnalysisResult } from "./aiTypes";
import type { IncidentReport } from "../engines/generateIncidentReport";

export function buildDeterministicAIAnalysis(
  report: IncidentReport,
): AIAnalysisResult {
  const activeIncidents = report.incidentLifecycle.activeIncidents ?? [];
  const diagnosis =
    report.rootCause?.category && report.rootCause?.subcategory
      ? `${report.rootCause.category} - ${report.rootCause.subcategory}`
      : "Infrastructure health degradation detected.";
  const evidence = [
    ...(report.rootCause?.evidence ?? []),
    ...report.correlations.flatMap((finding) => finding.evidence ?? []),
  ].slice(0, 10);
  const nextActions: string[] = [];
  nextActions.push("kubectl get nodes");
  nextActions.push("kubectl describe nodes");
  nextActions.push("kubectl get pods");
  const hasApplicationFailure = activeIncidents.some(
    (incident) =>
      incident.issue === "LivenessProbeFailure" ||
      incident.issue === "ReadinessProbeFailure",
  );
  if (hasApplicationFailure) {
    nextActions.push(
      "kubectl rollout restart deployment/aiops-engine",
    );
  }
  const confidence = report.rootCause
    ? Math.min(report.rootCause.confidence / 100, 1)
    : 0.5;
  return {
    summary:
      report.rootCause?.evidence?.[0] ??
      "The AIOps pipeline detected one or more active infrastructure incidents.",
    diagnosis,
    rootCauseExplanation:
      report.rootCause
        ? `The strongest deterministic root-cause signal is ${report.rootCause.category} - ${report.rootCause.subcategory}.`
        : "No single deterministic root cause could be established.",
    impact:
      activeIncidents.length > 0
        ? `${activeIncidents.length} active incident(s) are currently affecting system health.`
        : "No active incidents are currently affecting system health.",
    riskExplanation:
      report.summary.level === "Critical"
        ? "The system is in a critical state and remediation should be handled cautiously."
        : report.summary.level === "Warning"
          ? "The system is degraded and remediation should be validated before infrastructure changes."
          : "The current system state presents limited remediation risk.",
    nextActions,
    confidence,
    evidenceUsed:
      evidence.length > 0
        ? evidence
        : ["Deterministic incident analysis produced no additional evidence."],
    limitations: [
      "This analysis was generated by the deterministic AIOps fallback because the AI provider was unavailable.",
      "The fallback does not provide the contextual reasoning capability of the external AI provider.",
      "Infrastructure-changing actions must still pass remediation policy and human approval.",
    ],
    generatedAt: new Date().toISOString(),
  };
}